[General]

; Glance at Pip-Boy map key. (Default: G)
; Key code list located here: https://geckwiki.com/index.php?title=IsKeyPressed
iKeybind = 34

; Enable controller support. (Grab + Pip-Boy Button)
bControllerSupport = 1

; Control Style. 0 = Hold, 1 = Toggle
iControlStyle = 0

; Forces the player to walk when looking at the Pip-Boy
bForceWalk = 0

; Scanline alpha. (Percentage)
iScanlineAlpha = 50

; Map render brightness in interior cells. 1.0 = Minimum
fBrightnessInterior = 1.3

; Map render brightness in exterior cells. 1.0 = Minimum
fBrightnessExterior = 1.75

; Apply a depth of field effect when looking at the Pip-Boy.
iDepthOfFieldStrength = 0

; Apply a depth of field effect when looking at the Pip-Boy.
iDepthOfFieldDistance = 0

; Realtime Pip-Boy screen refresh interval. (In frames)
iRefreshInterval = 1


[Developer]

; Enables the Pip-Boy editor. Only enable if you know what you're doing!
; ## CONTROLS ##
; Enter:					Open editor (While looking at realtime Pip-Boy)
; Enter:					Save Preset (While in editor)
; Backspace:				Exit editor
; Arrow Keys:				Move safe zone position
; Arrow Keys + Right Ctrl:	Move map position
; -/+ :						Move horizontal safe zone in/out
; -/+ + Right Ctrl:			Move vertical safe zone in/out
bEditor = 0
